# SQlite
jakarta.persistence.jdbc.url=jdbc:sqlite:/Users/croitoruandreea/Desktop/ANUL2/semestrul4/MPP/examen_practic/cuvinte/SUB3_2024/bd.sqlite

#create/none/update
jakarta.persistence.schema-generation.database.action=update

# SQL statement logging
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true
hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
hibernate.temp.use_jdbc_metadata_defaults=true


