<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Server\Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Home.cs">
      <SubType>Form</SubType> 
    </Compile>
    <Compile Update="Home.Designer.cs">
      <DependentUpon>Home.cs</DependentUpon>
    </Compile>
    <Compile Update="Login.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Login.Designer.cs">
      <DependentUpon>Login.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="bin\Debug\net8.0-windows\concurs.db" />
    <None Include="bin\Debug\net8.0-windows\concursDB" />
    <None Include="bin\Debug\net8.0-windows\mydatabase.db" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.0-preview.3.25171.5" />
  </ItemGroup>

</Project>